### PR TITLE
Move database versions to match oldest supported and latest released version

### PR DESCRIPTION
**Pull request by gmokki**

### CODE REVIEW

**Comment by efonsell** [comment]
Tests are failing

**Review by efonsell — CHANGES_REQUESTED** [review]
Tests are failing

**Review by efonsell — APPROVED** [review]

**Review by efonsell — APPROVED** [review]
Remember to update github wiki pages as well (supported/tested db versions)

**Review by efonsell — APPROVED** [review]
Please update the wiki page https://github.com/NitorCreations/nflow/wiki/Supported-Java-and-database-engine-versions

**Comment by gmokki** [comment]
Newer version bump was just merged

**Pull request closed without merging**
